/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ArquivosDao;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import main.Principal;
import util.Alexa;
import util.FabricaArquivo;

/**
 *
 * @author Admin
 */
public class ClienteInserirForm extends javax.swing.JFrame {

    String tipoImagem = "";
    String urlOrigemImagem = "";
    boolean usuarioEscolheuUmaImagem = false;

    /**
     * Creates new form ClienteInserirForm
     */
    public ClienteInserirForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        retornarAoMenuPrincipalButton = new javax.swing.JButton();
        retornarAoMenuDeClientesButton = new javax.swing.JButton();
        nomeLabel = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        masculinoRadioButton = new javax.swing.JRadioButton();
        femininoRadioButton = new javax.swing.JRadioButton();
        naoInformarRadioButton = new javax.swing.JRadioButton();
        dataNascDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enderecoTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        celularTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        observacaoTextArea = new javax.swing.JTextArea();
        imageLabel = new javax.swing.JLabel();
        escolherImagemButton = new javax.swing.JButton();
        salvarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        retornarAoMenuPrincipalButton.setText("RETORNAR AO MENU PRINCIPAL");
        retornarAoMenuPrincipalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retornarAoMenuPrincipalButtonActionPerformed(evt);
            }
        });

        retornarAoMenuDeClientesButton.setText("RETORNAR AO MENU DE CLIENTES");
        retornarAoMenuDeClientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retornarAoMenuDeClientesButtonActionPerformed(evt);
            }
        });

        nomeLabel.setText("NOME");

        buttonGroup1.add(masculinoRadioButton);
        masculinoRadioButton.setText("MASCULINO");
        masculinoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculinoRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(femininoRadioButton);
        femininoRadioButton.setText("FEMININO");

        buttonGroup1.add(naoInformarRadioButton);
        naoInformarRadioButton.setText("NÃO INFORMAR");

        jLabel1.setText("DATA DE NASCIMENTO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("CADASTRO CLIENTE");

        enderecoTextArea.setColumns(20);
        enderecoTextArea.setRows(5);
        jScrollPane1.setViewportView(enderecoTextArea);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ENDEREÇO");

        jLabel4.setText("CELULAR");

        jLabel5.setText("E-MAIL");

        jLabel6.setText("OBSERVAÇÃO");

        observacaoTextArea.setColumns(20);
        observacaoTextArea.setRows(5);
        jScrollPane2.setViewportView(observacaoTextArea);

        escolherImagemButton.setText("ESCOLHER IMAGEM");
        escolherImagemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolherImagemButtonActionPerformed(evt);
            }
        });

        salvarButton.setText("SALVAR");
        salvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(celularTextField))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(escolherImagemButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(salvarButton))
                            .addComponent(imageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataNascDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(masculinoRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(femininoRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(naoInformarRadioButton))
                            .addComponent(retornarAoMenuPrincipalButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(retornarAoMenuDeClientesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(nomeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(15, 15, 15)
                                .addComponent(emailTextField)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(1017, 1017, 1017))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retornarAoMenuPrincipalButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retornarAoMenuDeClientesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masculinoRadioButton)
                    .addComponent(femininoRadioButton)
                    .addComponent(naoInformarRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dataNascDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celularTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(escolherImagemButton)
                    .addComponent(salvarButton))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retornarAoMenuPrincipalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retornarAoMenuPrincipalButtonActionPerformed
        // TODO add your handling code here:
        MenuPrincipalForm menuPrincipalForm = new MenuPrincipalForm();
        menuPrincipalForm.setVisible(true);
        menuPrincipalForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_retornarAoMenuPrincipalButtonActionPerformed

    private void retornarAoMenuDeClientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retornarAoMenuDeClientesButtonActionPerformed
        // TODO add your handling code here:
        MenuClientesForm menuClientesForm = new MenuClientesForm();
        menuClientesForm.setVisible(true);
        menuClientesForm.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_retornarAoMenuDeClientesButtonActionPerformed

    private void masculinoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculinoRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masculinoRadioButtonActionPerformed

    private void escolherImagemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolherImagemButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();

        //Limit type of file name extensions supported.
        FileNameExtensionFilter filter = new FileNameExtensionFilter("4 Extensions Supported", "jpg", "png", "jpeg", "gif");

        fileChooser.setFileFilter(filter);

        int selected = fileChooser.showOpenDialog(null);

        //check if open button has been clicked.
        if (selected == JFileChooser.APPROVE_OPTION) {

            File file = fileChooser.getSelectedFile();

            //Get Path of the selected image.
            String getselectedImage = file.getAbsolutePath();

            if (getselectedImage.contains("jpg")) {
                System.out.println("imagem jpg");
                tipoImagem = "JPG";
            } else {
                if (getselectedImage.contains("png")) {
                    System.out.println("imagem png");
                    tipoImagem = "PNG";
                } else {
                    if (getselectedImage.contains("jpeg")) {
                        System.out.println("imagem jpeg");
                        tipoImagem = "JPEG";
                    } else {
                        System.out.println("imagem gif");
                        tipoImagem = "GIF";
                    }
                }
            }

            //Display image path on Message Dialog
            //JOptionPane.showMessageDialog(null, getselectedImage);
            urlOrigemImagem = getselectedImage;

            ImageIcon imIco = new ImageIcon(getselectedImage);

            //make image fit on jlabel.
            Image imFit = imIco.getImage();

            Image imgFit = imFit.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);

            imageLabel.setIcon(new ImageIcon(imgFit));

            usuarioEscolheuUmaImagem = true;

        }
    }//GEN-LAST:event_escolherImagemButtonActionPerformed

    private void salvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarButtonActionPerformed
        // TODO add your handling code here:
        Principal.cliente.setNome(nomeTextField.getText());
        if (masculinoRadioButton.isSelected()) {
            Principal.cliente.setGenero("MASCULINO");
        } else {
            if (femininoRadioButton.isSelected()) {
                Principal.cliente.setGenero("FEMININO");
            } else {
                if (naoInformarRadioButton.isSelected()) {
                    Principal.cliente.setGenero("NÃO INFORMAR");
                } else {
                    Alexa.escrevaJanela("Atenção, escolha uma opção de gênero.");
                    return;
                }
            }
        }
        Principal.cliente.setDt_nasc(dataNascDateChooser.getDate());
        Principal.cliente.setEndereco(enderecoTextArea.getText());
        Principal.cliente.setEmail(emailTextField.getText());
        Principal.cliente.setObservacao(observacaoTextArea.getText());
        Principal.cliente.setCelular(celularTextField.getText());
        
        if(usuarioEscolheuUmaImagem == false){
            Alexa.escrevaJanela("Escolha uma imagem de perfil para o \nusuário para concluir o cadastro...");
            return;
        }

        // Persistir dados no banco...
        
        Principal.clienteDao.inserir(Principal.cliente);
        Integer lastId = Principal.clienteDao.getUltimoId();
        System.out.println("" + lastId + "." + tipoImagem);
        Principal.cliente.setImagemPerfil("" + lastId + "." + tipoImagem);
        Principal.cliente.setId(lastId);
        Principal.clienteDao.atualizar(Principal.cliente);
        ArquivosDao.copiarFotoPerfilParaPastaDentroAplicacao(urlOrigemImagem, "" + lastId + "." + tipoImagem);

        Alexa.escrevaJanela("Registro salvo com sucesso!");

    }//GEN-LAST:event_salvarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteInserirForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteInserirForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteInserirForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteInserirForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteInserirForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField celularTextField;
    private com.toedter.calendar.JDateChooser dataNascDateChooser;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextArea enderecoTextArea;
    private javax.swing.JButton escolherImagemButton;
    private javax.swing.JRadioButton femininoRadioButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton masculinoRadioButton;
    private javax.swing.JRadioButton naoInformarRadioButton;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextArea observacaoTextArea;
    private javax.swing.JButton retornarAoMenuDeClientesButton;
    private javax.swing.JButton retornarAoMenuPrincipalButton;
    private javax.swing.JButton salvarButton;
    // End of variables declaration//GEN-END:variables
}
